Use more sensible names for path variables

diff --git a/git-deploy b/git-deploy
--- a/git-deploy
+++ b/git-deploy
@@ -43,17 +43,17 @@ fi
 
 # deduce paths and repo names
 
-FROMDIR=`pwd`
-FROM=`basename "$FROMDIR"`
-TO="${FROM/ /\\ }.git"
-TODIR="$FROMDIR.git"
+SRC_DIR=`pwd`
+SRC_REPO_NAME=`basename "$SRC_DIR"`
+DEST_REPO_NAME="${SRC_REPO_NAME/ /\\ }.git"
+DEST_DIR="$SRC_DIR.git"
 
 
 # check whether we are in the root dir of a git-managed repository
 
-if [[ ! -d "$FROMDIR/.git" ]] ; then
-    echo "ERROR: Directory '$FROMDIR/.git' not found." >&2
-    echo "ERROR: '$FROMDIR' does not appear to be a git repository." >&2
+if [[ ! -d "$SRC_DIR/.git" ]] ; then
+    echo "ERROR: Directory '$SRC_DIR/.git' not found." >&2
+    echo "ERROR: '$SRC_DIR' does not appear to be a git repository." >&2
     exit 1
 fi
 
@@ -72,15 +72,15 @@ fi
 
 # create a remote copy of the repo
 
-git clone --bare "$FROMDIR" "$TODIR"
-scp -r "$TODIR" "$SSH_PATH"
+git clone --bare "$SRC_DIR" "$DEST_DIR"
+scp -r "$DEST_DIR" "$SSH_PATH"
 
-rm -rf "$TODIR"
+rm -rf "$DEST_DIR"
 
 
 # save info about the remote repo
 
-git config remote.$REMOTE.url "$SSH_PATH/$TO"
+git config remote.$REMOTE.url "$SSH_PATH/$DEST_REPO_NAME"
 git config remote.$REMOTE.fetch "+refs/heads/*:refs/remotes/$REMOTE/*"
 
 if [[ "$REMOTE" == "origin" ]] ; then
